version: '3'

services:

  db:
    image: postgres:12-alpine
    container_name: telegram-api-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=telegram
      - POSTGRES_PASSWORD=telegram
      - POSTGRES_DB=telegram